---
title: "HW3"
author: "Eric Morris"
date: "10/5/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

# install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")
```


## Problem 1 

Loading in the BRFSS Data: 

```{r BRFSS Data Import}
library(p8105.datasets)

brfss_data = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  mutate(response_factor = as.factor(response)) %>% 
  rename(state = locationabbr, county = locationdesc)
```

In 2002, which states were observed at 7 locations?

```{r}
brfss_data %>% 
  group_by(state) %>% 
  distinct(county) %>% 
  summarize(n = n()) %>% 
  View()
```

CT, MT, NH, NM, OR, TN, UT were observed at 7 locations.

Make a “spaghetti plot” that shows the number of observations in each state from 2002 to 2010.

```{r}
ggplot(brfss_data, aes(x = year, y = sample_size, color = name) +
         geom_line(data = brfss_data)
```

